siteURL: "https://example.org"  # Replace with the URL of your site; Please do not add a trailing slash
title: "Bestatic | The Best Static Site Generator!"
description: "A simple but powerful static-site generator that transforms markdown texts to webpages and blogs"
theme: Amazing
number_of_pages: 4  # Enter the number of blog pages to paginate blog posts
comments:
  enabled: true
  system: giscus # Enter "disqus" or "giscus" here.
  comment_system_id: "tatsatb/giscus-test"
rss_feed: true
homepage_type: default # Enter "default" or "list"
enable_inject_tag: true # default is true
