name: bestatic # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.0.24' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple but powerful static-site generator, written in Python. # 79 char long summary
description: |
  Bestatic is a flexible and simple static-site generator, written in Python and Jinja2 templating engine. It is truly minimal, yet fully-featured. Unlike most of the existing static-site genrators,
  it can be installed graphically, without touching command line.
  On the other hand, like every other static-site generator, 
  Bestatic can generate a complete website by processing a bunch of markdown files. 
  As a result, it eliminates the need for server-side programming or databases. 
  The site Bestatic generates can be served from any 
  web server or host (or even GitHub pages or GitLab pages). 


confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

parts:
  bestatic:
    source: .
    plugin: python
    python-packages:
    - Bestatic==0.0.24


apps:
  bestatic:
    command:
      "bin/bestatic"
    plugs:
      - network
      - network-bind
      - home

